# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSConvLSTMModuleV3
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32  # Total temporal receptive field of 125 samples given 4 layers
  batch_norm: False
  layer_norm: False
  rnn_config: 
    num_layers: 1
    bidirection: True
    dropout: 0.6
    layer_norm: True
    batch_norm: False
    rnn_dim: 128

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
